### ISSUE TITLE
Error when 2 corner windows

### ISSUE THREAD

**Issue by SnowyEgret** [SnowyEgret/frameup#8]
```ruby
Error: #<RuntimeError: Could not find a face on point>
C:/Users/Duncan/SketchUp Extensions/FrameUp/src/ds_frameup/trimmable.rb:89:in `face_on_point'
C:/Users/Duncan/SketchUp Extensions/FrameUp/src/ds_frameup/trimmable.rb:75:in `block in delete_offcuts'
C:/Users/Duncan/SketchUp Extensions/FrameUp/src/ds_frameup/trimmable.rb:69:in `each'
C:/Users/Duncan/SketchUp Extensions/FrameUp/src/ds_frameup/trimmable.rb:69:in `delete_offcuts'
C:/Users/Duncan/SketchUp Extensions/FrameUp/src/ds_frameup/trimmable.rb:48:in `block in subtract'
C:/Users/Duncan/SketchUp Extensions/FrameUp/src/ds_frameup/trimmable.rb:37:in `each'
C:/Users/Duncan/SketchUp Extensions/FrameUp/src/ds_frameup/trimmable.rb:37:in `subtract'
C:/Users/Duncan/SketchUp Extensions/FrameUp/src/ds_frameup/perimeter.rb:57:in `frame'
C:/Users/Duncan/SketchUp Extensions/FrameUp/src/ds_frameup/panel.rb:113:in `frame_perimeter'
C:/Users/Duncan/SketchUp Extensions/FrameUp/src/ds_frameup/panel.rb:93:in `frame'
C:/Users/Duncan/SketchUp Extensions/FrameUp/src/ds_frameup/panel.rb:454:in `test'
```

**Comment by SnowyEgret** [comment]
Happens when panel is modified to have first corner window, but not on original test model
